const ERROR_CODES = Object.freeze({
  OK: 0,
  UNKNOWN: 1,
  INVALID_INPUT: 400,
  UNAUTHORIZED: 401,
  SPACE_FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  BACKUP_EXPORT_FAILED: 460,
  BACKUP_IMPORT_INVALID: 461,
  BACKUP_VERSION_UNSUPPORTED: 462,
  BACKUP_FILE_MISSING: 463,
  BACKUP_RESTORE_FAILED: 464
})

module.exports = {
  ERROR_CODES
}
