import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

describe('meal-plans page template', () => {
  it('renders hero, collapsible calendar, and inventory check modal structure', () => {
    const template = readFileSync('miniprogram/pages/meal-plans/index.wxml', 'utf8')

    expect(template).toContain('plans-hero')
    expect(template).toContain('/images/meal-plans-hero.svg')
    expect(template.includes('/images/meal-plans-hero.jpg')).toBe(false)
    expect(template).toContain('plans-hero__topbar')
    expect(template).toContain('plans-hero__date-pill')
    expect(template).toContain('plans-hero__stat-pill')
    expect(template).toContain('calendar-panel')
    expect(template).toContain('calendar-grid')
    expect(template).toContain('calendar-panel__viewport')
    expect(template).toContain('bindtap="goPrevMonth"')
    expect(template).toContain('bindtap="goNextMonth"')
    expect(template).toContain('bindtap="goToday"')
    expect(template).toContain('size="small"')
    expect(template).toContain('t-class="calendar-nav__today"')
    expect(template).toContain('bindtap="toggleCalendarExpanded"')
    expect(template).toContain('bindtap="openInventoryCheck"')
    expect(template).toContain('handleToggleMealPlanStatus')
    expect(template).toContain('showMealPlanStatusModal')
    expect(template).toContain('meal-plan-status-modal')
    expect(template).toContain('selectMealPlanStatus')
    expect(template).toContain('removeSelectedMealPlan')
    expect(template).toContain('class="{{item.itemClass}}"')
    expect(template).toContain('catchtap="selectMealPlanStatus"')
    expect(template).toContain('handlePlanRecipeTap')
    expect(template).toContain('handleSelectMealPlan')
    expect(template).toContain('plan-card__tool plan-card__tool--edit')
    expect(template).toContain('statusToolClass')
    expect(template).toContain('plan-card__recipe-tag')
    expect(template.includes('{{item.mealTypeLabel}}：{{item.primaryRecipeName}}')).toBe(false)
    expect(template).toContain('plans-day-card__action plans-day-card__action--create')
    expect(template).toContain('inventory-modal')
    expect(template).toContain('inventory-item__checkbox')
    expect(template).toContain('inventory-item--missing')
    expect(template).toContain('inventory-item--ok')
    expect(template).toContain('bindtap="toggleInventorySelection"')
    expect(template).toContain('generateShoppingList')
  })

  it('uses animated calendar viewport styles and modal cards instead of a floating fab list', () => {
    const styles = readFileSync('miniprogram/pages/meal-plans/index.wxss', 'utf8')

    expect(styles).toMatch(/\.meal-plans-page\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
    expect(styles).toMatch(/\.plans-hero__overlay\s*\{[\s\S]*align-items:\s*stretch;/)
    expect(styles.includes('linear-gradient(135deg, var(--brand-strong')).toBe(false)
    expect(styles).toMatch(/\.plans-hero__topbar\s*\{[\s\S]*display:\s*flex;[\s\S]*justify-content:\s*space-between;/)
    expect(styles).toMatch(/\.plans-hero__date-pill\s*\{[\s\S]*width:\s*fit-content;/)
    expect(styles).toMatch(/\.plans-hero__stat-pill\s*\{[\s\S]*width:\s*fit-content;/)
    expect(styles).toMatch(/\.plans-hero__subtitle\s*\{[\s\S]*white-space:\s*nowrap;[\s\S]*text-overflow:\s*ellipsis;/)
    expect(styles).toMatch(/\.calendar-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(7,/)
    expect(styles).toMatch(/\.t-button\.calendar-nav__today\s*\{[\s\S]*width:\s*auto;[\s\S]*margin-left:\s*0;[\s\S]*margin-right:\s*0;[\s\S]*min-width:\s*0;[\s\S]*padding-left:\s*12rpx;[\s\S]*padding-right:\s*12rpx;/)
    expect(styles).toMatch(/\.t-button\.plans-day-card__action--inventory\s*\{[\s\S]*width:\s*auto;[\s\S]*min-width:\s*0;/)
    expect(styles).toMatch(/\.calendar-panel__viewport\s*\{[\s\S]*overflow:\s*hidden;[\s\S]*transition:/)
    expect(styles).toMatch(/\.calendar-cell\s*\{[\s\S]*height:\s*88rpx;[\s\S]*box-sizing:\s*border-box;[\s\S]*border-radius:\s*22rpx;/)
    expect(styles).toMatch(/\.calendar-cell__day\s*\{[\s\S]*font-size:\s*28rpx;/)
    expect(styles).toMatch(/\.calendar-cell__dot\s*\{[\s\S]*margin-top:\s*6rpx;/)
    expect(styles).toMatch(/\.calendar-cell--selected\s*\{/)
    expect(styles).toMatch(/\.calendar-cell--outside-month\s*\{/)
    expect(styles).toMatch(/\.calendar-toggle__chevron--expanded\s*\{[\s\S]*transform:\s*rotate\(180deg\);/)
    expect(styles).toMatch(/\.inventory-modal__summary\s*\{[\s\S]*display:\s*grid;/)
    expect(styles).toMatch(/\.inventory-modal__panel\s*\{[\s\S]*min-width:\s*500rpx;[\s\S]*max-width:\s*720rpx;[\s\S]*box-sizing:\s*border-box;/)
    expect(styles).toMatch(/\.inventory-item--ok\s*\{[\s\S]*background:/)
    expect(styles).toMatch(/\.inventory-item--missing\s*\{[\s\S]*background:/)
    expect(styles).toMatch(/\.inventory-item__checkbox\s*\{/)
    expect(styles).toMatch(/\.inventory-item__checkbox--selected\s*\{/)
    expect(styles).toMatch(/\.inventory-modal__primary\s*\{[\s\S]*min-height:\s*92rpx;/)
    expect(styles).toMatch(/\.plans-day-card__action--create\s*\{[\s\S]*background:\s*linear-gradient/)
    expect(styles).toMatch(/\.plans-day-card__action--create\s*\{[\s\S]*color:\s*#fff;/)
    expect(styles).toMatch(/\.plan-card__tools\s*\{[\s\S]*display:\s*flex;/)
    expect(styles).toMatch(/\.plan-card__tool--status\s*\{/)
    expect(styles).toMatch(/\.plan-card__recipe-tag\s*\{/)
    expect(styles).toMatch(/\.plan-card__icon\s*\{[\s\S]*background:\s*var\(--surface-muted,\s*#f3f4f7\);/)
    expect(styles).toMatch(/\.meal-plan-status-modal__overlay\s*\{/)
    expect(styles).toMatch(/\.meal-plan-status-chip--active\s*\{/)
    expect(styles).toMatch(/\.meal-plan-status-chip--active\s*\{[\s\S]*border-color:/)
    expect(styles).toMatch(/\.meal-plan-status-modal__recipe-item\s*\{[\s\S]*background:\s*var\(--surface-muted,\s*#f3f4f7\);/)
    expect(styles).toMatch(/\.meal-plan-status-modal__delete\s*\{/)
    expect(styles).not.toMatch(/\.fab-add\s*\{[\s\S]*position:\s*fixed;/)
  })

  it('uses theme variables for the meal plans hero and page surface', () => {
    const styles = readFileSync('miniprogram/pages/meal-plans/index.wxss', 'utf8')

    expect(styles).toContain('var(--page-bg')
    expect(styles).toContain('var(--surface-bg')
    expect(styles).toContain('var(--surface-muted')
    expect(styles).toContain('var(--brand')
    expect(styles).toContain('var(--brand-strong')
    expect(styles).toContain('var(--text-primary')
    expect(styles).toContain('var(--text-secondary')
    expect(styles).toContain('var(--text-tertiary')
    expect(styles).toContain('var(--border-soft')
    expect(styles).toContain('var(--shadow-soft')
  })
})
