import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

describe('pantry edit template', () => {
  it('does not block selecting past expiration dates in date picker', () => {
    const template = readFileSync('miniprogram/pages/pantry-edit/index.wxml', 'utf8')
    expect(template.includes('start="{{today}}"')).toBe(false)
  })

  it('uses a sectioned editor layout with fixed bottom actions', () => {
    const template = readFileSync('miniprogram/pages/pantry-edit/index.wxml', 'utf8')

    expect(template).toContain('editor-shell')
    expect(template).toContain('bottom-actions')
    expect(template).toContain('footer-close-button')
    expect(template).toContain('footer-submit-button')
    expect(template).toContain('基本信息')
    expect(template).toContain('库存信息')
    expect(template).toContain('bindchange="handleCategorySelect"')
    expect(template).toContain('bindchange="handleLocationSelect"')
    expect(template).toContain('bindchange="handleUsageStatusSelect"')
    expect(template).toContain('detail-grid detail-grid--basic')
    expect(template).toContain('detail-grid detail-grid--schedule')
    expect(template).toContain('placeholder="例如：牛奶"')
    expect(template).toContain('>状态</view>')
    expect(template).toContain('quantity-stepper')
    expect(template).toMatch(/<view class="stepper-button" bindtap="decrementQuantity">−<\/view>/)
    expect(template).toMatch(/<view class="stepper-button" bindtap="incrementQuantity">＋<\/view>/)
    expect(template).toMatch(/<view class="stepper-button" bindtap="decrementShelfLifeMonths">−<\/view>/)
    expect(template).toMatch(/<view class="stepper-button" bindtap="incrementShelfLifeMonths">＋<\/view>/)
    expect(template).toContain('bindchange="handleProductionDateChange"')
    expect(template).toContain('bindchange="handleExpirationDateChange"')
    expect(template).toContain('bindchange="handleOpenedDateChange"')
    expect(template).toContain('过期日期')
    expect(template).toContain('bindtap="clearCategory"')
    expect(template).toContain('bindtap="clearLocation"')
    expect(template).toContain('bindtap="clearExpirationDate"')
    expect(template).toContain('bindtap="clearOpenedDate"')
  })

  it('keeps notes textarea and delete action compact instead of full width', () => {
    const styles = readFileSync('miniprogram/pages/pantry-edit/index.wxss', 'utf8')

    expect(styles).toMatch(/\.field-textarea--notes\s*\{[\s\S]*min-height:\s*8\d?rpx;/)
    expect(styles).toMatch(/\.delete-button\s*\{[\s\S]*width:\s*auto;/)
    expect(styles).toMatch(/\.delete-button\s*\{[\s\S]*align-self:\s*flex-start;/)
    expect(styles).toMatch(/\.edit-page\s*\{[\s\S]*overflow-x:\s*hidden;/)
    expect(styles).toMatch(/\.editor-section__head\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;/)
    expect(styles).toMatch(/\.editor-section__title\s*\{[\s\S]*white-space:\s*nowrap;/)
    expect(styles).toMatch(/\.form-row__label\s*\{[\s\S]*width:\s*9\d?rpx;/)
    expect(styles).toMatch(/\.detail-grid--basic,\s*\.detail-grid--schedule\s*\{/)
    expect(styles).toMatch(/@media\s*\(max-width:\s*720rpx\)\s*\{[\s\S]*\.detail-grid\s*\{[\s\S]*grid-template-columns:\s*1fr;/)
    expect(styles).toMatch(/\.detail-grid__item\s*\{[\s\S]*display:\s*grid;[\s\S]*align-content:\s*start;/)
    expect(styles).toMatch(/\.field-input--inline\s*\{[\s\S]*flex:\s*1;/)
    expect(styles).toMatch(/\.stepper-button\s*\{[\s\S]*flex:\s*none;[\s\S]*width:\s*88rpx;[\s\S]*height:\s*88rpx;/)
    expect(styles).toMatch(/\.stepper-button\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;[\s\S]*justify-content:\s*center;/)
    expect(styles).toMatch(/\.stepper-button\s*\{[\s\S]*border:\s*1px solid #edf0f4;/)
    expect(styles).toMatch(/\.stepper-value\s*\{[\s\S]*height:\s*88rpx;/)
    expect(styles).toMatch(/\.stepper-value\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;[\s\S]*justify-content:\s*center;/)
    expect(styles).toMatch(/\.field-picker-row\s*\{[\s\S]*display:\s*flex;/)
    expect(styles).toMatch(/\.field-picker-row\s*\{[\s\S]*align-items:\s*stretch;/)
    expect(styles).toMatch(/\.field-picker-row\s*\{[\s\S]*position:\s*relative;/)
    expect(styles).toMatch(/\.field-clear\s*\{[\s\S]*position:\s*absolute;[\s\S]*right:\s*18rpx;/)
    expect(styles).toMatch(/\.field-input--with-clear\s*\{[\s\S]*padding-right:\s*72rpx;/)
    expect(styles).toMatch(/\.field-clear\s*\{[\s\S]*background:\s*rgba\(/)
    expect(styles).toMatch(/\.field-clear\s*\{[\s\S]*border:\s*1px solid rgba\(/)
    expect(styles).toMatch(/\.field-clear\s*\{[\s\S]*opacity:\s*0\.\d+;/)
    expect(styles).toMatch(/\.bottom-actions\s*\{[\s\S]*position:\s*fixed;/)
    expect(styles).toMatch(/\.quantity-stepper\s*\{[\s\S]*gap:\s*10rpx;/)
    expect(styles).toMatch(/\.stepper-button\s*\{[\s\S]*border-radius:\s*18rpx;/)
    expect(styles).toMatch(/\.stepper-value\s*\{[\s\S]*padding:\s*0 16rpx;/)
  })
})
